#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-commons-digester
Version  : 1.6
Release  : 2
URL      : https://repo1.maven.org/maven2/commons-digester/commons-digester/1.6/commons-digester-1.6.jar
Source0  : https://repo1.maven.org/maven2/commons-digester/commons-digester/1.6/commons-digester-1.6.jar
Source1  : https://repo1.maven.org/maven2/commons-digester/commons-digester/1.6/commons-digester-1.6.pom
Source2  : https://repo1.maven.org/maven2/commons-digester/commons-digester/1.8/commons-digester-1.8.jar
Source3  : https://repo1.maven.org/maven2/commons-digester/commons-digester/1.8/commons-digester-1.8.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-commons-digester-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-commons-digester package.
Group: Data

%description data
data components for the mvn-commons-digester package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-digester/commons-digester/1.6
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/commons-digester/commons-digester/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-digester/commons-digester/1.6
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/commons-digester/commons-digester/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-digester/commons-digester/1.8
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/commons-digester/commons-digester/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-digester/commons-digester/1.8
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/commons-digester/commons-digester/1.8


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/commons-digester/commons-digester/1.6/commons-digester-1.6.jar
/usr/share/java/.m2/repository/commons-digester/commons-digester/1.6/commons-digester-1.6.pom
/usr/share/java/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1.8.jar
/usr/share/java/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1.8.pom
